# config/defaults.R

DEFAULT_REF_PROTEIN <- "ENTQQEEQDYDYGTDTCPFPVLANKTNKAKFVGCHQKCNGGDQKLTDGTACYVVERKVWDRMTPMLWYECPLGECKNGVCEDLRKKEDCRKGNGEEK"

DEFAULT_LEFT_FLANK <- "GGTGGCAGCGGTGGATCC"

DEFAULT_RIGHT_FLANK <- "CTCGAGGGCGGTGGCG"

DEFAULT_MIN_COUNT <- 10

DEFAULT_MIN_FREQ <- 0